# Generated by Django 5.0.6 on 2024-05-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50)),
                ('car_manufacturer', models.CharField(max_length=50)),
                ('car_year', models.IntegerField()),
                ('car_price', models.FloatField()),
                ('car_engine', models.CharField(max_length=10)),
            ],
        ),
    ]
